Repository datacarpentry/python-ecology-lesson, pull requests merged in 2020-06, with the labels that each got.

#462 Pr/421
  _episodes/05-merging-data.md
  data/portal-teachingdb-master.zip
  setup.md
Labels: status:in progress

#461 add reminder about plotline installation
  _episodes/07-visualization-ggplot-python.md
Labels: type:enhancement

#460 Hot007 issue307 update guide
  _extras/guide.md
Labels: status:in progress, type:enhancement
