Repository datacarpentry/python-ecology-lesson, pull requests merged in 2023-04, with the labels that each got.

#477 PR to address issue #471
  _episodes/00-before-we-start.md
Labels: type:bug

#519 Add alt text for 06_color_plot.png
  _episodes/07-visualization-ggplot-python.md
Labels: type:accessibility

#521 Add alt text for 06_select_plot.png
  _episodes/07-visualization-ggplot-python.md
Labels: type:accessibility

#540 Update to final version of styles lesson template
  .github/PULL_REQUEST_TEMPLATE.md
  _includes/check_transition_variables.html
  _includes/lesson_footer.html
  _includes/life_cycle.html
  _includes/navbar.html
  _layouts/base.html
  assets/css/lesson.scss
  bin/boilerplate/_config.yml
Labels: type:template and tools

#452 Explains attribute and method
  _episodes/02-starting-with-data.md
Labels: type:clarification

#438 Add a reminder about what the question mark does
  _episodes/06-loops-and-functions.md
Labels: status:waiting for response, type:clarification
